-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "firstName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "homeCity" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isPilot" BOOLEAN NOT NULL DEFAULT false;
