export const AIRCRAFT_PRESETS = [
  {
    key: "c172s",
    family: "ga_piston",
    manufacturer: "Cessna",
    model: "172S Skyhawk",
    label: "Cessna 172S Skyhawk",
    description: "Monomotor pistão leve, excelente base de treino e navegação VFR/IFR leve.",
    defaults: {
      cruiseMode: "auto",
      usableFuelL: 201,
      tasKt: 122,
      fuelFlowCruiseLph: 34,
      taxiFuelL: 8,
      climbTimeMin: 14,
      climbFuelL: 18,
      descentTimeMin: 10,
      descentFuelL: 5,
      approachFuelL: 4,
      alternateFuelL: 24,
      contingencyPct: 5,
      finalReserveMin: 45,
      extraFuelL: 0,
      desiredLandingFuelL: 34,
      defaultCruiseAltFt: 6500,
      payloadKg: 300,
      reserveRule: "IFR 45 min",
    },
  },
  {
    key: "c182t",
    family: "ga_piston",
    manufacturer: "Cessna",
    model: "182T Skylane",
    label: "Cessna 182T Skylane",
    description: "Monomotor pistão de maior carga útil e cruzeiro mais forte para pernas regionais.",
    defaults: {
      cruiseMode: "auto",
      usableFuelL: 329,
      tasKt: 142,
      fuelFlowCruiseLph: 52,
      taxiFuelL: 10,
      climbTimeMin: 15,
      climbFuelL: 28,
      descentTimeMin: 10,
      descentFuelL: 6,
      approachFuelL: 5,
      alternateFuelL: 32,
      contingencyPct: 5,
      finalReserveMin: 45,
      extraFuelL: 0,
      desiredLandingFuelL: 45,
      defaultCruiseAltFt: 8500,
      payloadKg: 400,
      reserveRule: "IFR 45 min",
    },
  },
  {
    key: "pa28-181",
    family: "ga_piston",
    manufacturer: "Piper",
    model: "PA-28-181 Archer",
    label: "Piper PA-28 Archer",
    description: "Perfil estável para instrução avançada e navegação em aviação geral.",
    defaults: {
      cruiseMode: "auto",
      usableFuelL: 181,
      tasKt: 128,
      fuelFlowCruiseLph: 36,
      taxiFuelL: 8,
      climbTimeMin: 14,
      climbFuelL: 17,
      descentTimeMin: 9,
      descentFuelL: 4,
      approachFuelL: 4,
      alternateFuelL: 22,
      contingencyPct: 5,
      finalReserveMin: 45,
      extraFuelL: 0,
      desiredLandingFuelL: 32,
      defaultCruiseAltFt: 6500,
      payloadKg: 310,
      reserveRule: "IFR 45 min",
    },
  },
  {
    key: "bonanza-a36",
    family: "ga_piston",
    manufacturer: "Beechcraft",
    model: "Bonanza A36",
    label: "Beechcraft Bonanza A36",
    description: "Monomotor pistão executivo de maior velocidade e autonomia para navegação cruzada.",
    defaults: {
      cruiseMode: "auto",
      usableFuelL: 281,
      tasKt: 165,
      fuelFlowCruiseLph: 56,
      taxiFuelL: 10,
      climbTimeMin: 16,
      climbFuelL: 30,
      descentTimeMin: 10,
      descentFuelL: 5,
      approachFuelL: 5,
      alternateFuelL: 32,
      contingencyPct: 5,
      finalReserveMin: 45,
      extraFuelL: 0,
      desiredLandingFuelL: 48,
      defaultCruiseAltFt: 9500,
      payloadKg: 360,
      reserveRule: "IFR 45 min",
    },
  },
];

export function getAircraftPresetByKey(key) {
  return AIRCRAFT_PRESETS.find((item) => item.key === key) || null;
}

export function serializeAircraftPreset(preset) {
  if (!preset) return null;
  return {
    ...preset,
    defaults: { ...(preset.defaults || {}) },
  };
}
